project:
  type: book
  output-dir: docs

book:
  title: "Orange County Community Health Assessment 2025"
  subtitle: "Mid-Hudson Regional CHA"
  author: "Orange County Department of Health"
  chapters:
    - index.qmd
    - chapters/00-acknowledgements.qmd
    - chapters/00-contact-information.qmd
    - chapters/01-excutive_summary.qmd
    - chapters/01-introduction.qmd
    - chapters/02-area-being-assessed.qmd
    - chapters/03-demographics.qmd
    - chapters/04-Social and Physical Determinants of Health.qmd
    - chapters/05-health-behaviors.qmd
    - chapters/06-clinical-care.qmd
    - chapters/07-physical-environment.qmd
    - chapters/08-appendix.qmd
  sidebar:
    style: docked
    search: true
    collapse-level: 2

format:
  html:
    theme:
      - flatly
      - theme.scss
    css: custom-citation-styles.css
    toc: true
    toc-depth: 3
    page-layout: full
    code-fold: true
    code-tools: true
    number-sections: true
    smooth-scroll: true
    fig-cap-location: top
    tbl-cap-location: top

execute:
  freeze: auto
  working-dir: project
