---
title: "Mid-Hudson Regional Community Health Assessment 2025"
jupyter: python3
execute:
  freeze: false
page-layout: full
---

::: {.hero}
A living, data-driven assessment of the Mid-Hudson Regional Community Health Assessment's health status, priorities, and community conditions.
:::

## Population Focus for The Mid-Hudson Regional Community Health Assessment

-   Dutchess County
-   Orange County
-   Putnam County
-   Rockland County
-   Sullivan County
-   Ulster County
-   Westchester County

## Questions or Comments About the Assessment

For questions about the Mid-Hudson Regional, please contact:

### Dutchess County

>**Jennifer Conflitti, MPH**\
> Epidemiologist\
> [JConflitti@dutchessny.gov](mailto:JConflitti@dutchessny.gov)

### Orange County

>**Jackie Lawler, MPH, CPH**\
> Director of Epidemiology and Public Health Planning\
> [JLawler@orangecountygov.com](mailto:JLawler@orangecountygov.com)

### Putnam County

>**Alison Kaufman, DVM, MPH**\
> Senior Epidemiologist\
> [Alison.Kaufman@putnamcountyny.gov](mailto:Alison.Kaufman@putnamcountyny.gov)

### Rockland County

>**Peter Hornberger, MPH**\
> Director of Epidemiology and Public Health Planning\
> [Hornberp@co.rockland.ny.us](mailto:Hornberp@co.rockland.ny.us)

### Sullivan County

>**Jessie Moore, DrPH, MPH, CHES**\
> Public Health Director\
> [Jessie.Moore@sullivanny.gov](mailto:Jessie.Moore@sullivanny.gov)

### Westchester County

>**Jiali Li, Ph.D., M.A.**\
> Director of Research and Evaluation\
> [JAL6@westchestercountyny.gov](mailto:JAL6@westchestercountyny.gov)