---
title: Area Being Assessed
---

## The Mid-Hudson Region

The Mid-Hudson (M-H) region is comprised of seven-counties in New York
State (NYS) that is a mix of urban, suburban, and rural communities.
Located north of New York City (NYC), it comprises 12.1% of the NYS
population [@tbl-population-demographics]. The seven counties are Dutchess, Orange, Putnam,
Rockland, Sullivan, Ulster, and Westchester counties. The population is
becoming more ethnically diverse, with particular growth in Hispanic
communities [@tbl-ethnicity and @tbl-race]. The M-H Region, like the nation, is
aging with the fastest growing demographic, those being over 60 years
old.

The M-H region borders NYC and New Jersey to the south; New Jersey and
Pennsylvania to the west; Greene and Columbia counties to the north; and
Massachusetts and Connecticut to the east. See map in [Appendix
A](#AppendixA_MidHudsonRegionMap). The Region is a topically diverse
landscape with the rural Catskill Mountains, the Shawangunk Ridge, parts
of the NYC watershed, and the Hudson River flowing through it.

The Region benefits from its close proximity to NYC. Commuter rail lines
and many highways make travel easy for commuters. Major industries
include healthcare, education, retail, and government. Tourism is a
major economic driver with extensive parklands, historic landmarks,
arts, culture, shopping, and recreational activities. There are over 40
colleges and universities leading to a highly educated workforce [@tbl-education].

### Dutchess County

Dutchess County is in the center of the M-H Region, midway between NYC
and NYS’ capital, Albany. The western border includes 30 miles of Hudson
River shoreline with Connecticut forming the eastern border. Dutchess
County is 825 square miles, made up of 30 municipalities, consisting of
two cities, 20 towns, and eight villages. Dutchess County has 13 public
school districts and is also home to five colleges and universities. The
southwestern region of Dutchess County is the most densely populated
part of the county and includes the cities of Beacon and the county
seat, Poughkeepsie. The rest of the county is predominantly suburban and
rural. See map in [Appendix B](#section-1).

### Orange County

Orange County is located approximately 40 miles north of NYC. The county
is positioned between the Hudson River in the east and the Delaware
River in the west, the only county in NYS to border both rivers. Ulster
and Sullivan Counties border Orange County on the north, and Rockland
County is located to the south. The states of New Jersey and
Pennsylvania are located on the southwest borders of the county. Orange
County is 812 square miles [@tbl-area-and-population] and is a diverse mix of rural,
farmland, suburban, and urban areas. Orange County communities include
three cities, 21 towns, and 19 villages. Nearly 17% of the county’s
total population resides in its three cities of Middletown, Newburgh,
and Port Jervis.<sup>7</sup> Orange County has 19 public school
districts and is also home to four colleges, universities, and medical
schools. See map in [Appendix C](#section-2).

### Putnam County

Approximately 60 miles north of New York City, Putnam County blends
suburban neighborhoods, lake front communities, rural areas, farmlands,
parklands, and reservoirs. It is bordered by Connecticut to the east,
the Hudson River to the west, Dutchess County to the north and
Westchester County to the south. Six towns and three villages comprise
the 230-square-mile county. There are six public school districts and no
colleges or universities. Open space dominates its landscape,
highlighted by Clarence Fahnestock State Park, a preserve covering
nearly 10% of the county’s total area. See map in [Appendix
D](#section-3).

### Rockland County

Rockland County is located approximately 30 miles north and west of NYC
on the west side of the Hudson River. The county is a popular residence
for people who commute to jobs in nearby Westchester and Bergen
Counties, as well as NYC. Rockland County is bordered by Orange County
to the north and New Jersey to the south and west. Home to eight public
school districts and four colleges and universities, the 199-square mile
area of Rockland County includes five towns and 18 villages. This county
of 120,000 acres is designated a Preserve America Community, containing
more than 35,000 acres of preserved open space and parkland, just under
one third of the county by area. See map in [Appendix E](#section-4).

### Sullivan County

Sullivan County is a rural community in the northwestern part of the M-H
Region. It is located approximately 75 miles northwest of NYC in the
Catskill Mountains. The county is bordered by Delaware County to the
north, Ulster County to the east, Orange County to the south, and
Pennsylvania to the west. Home to seven public school districts and one
two-year college, the 997-square mile area includes 15 towns and seven
villages. See map in [Appendix F](#section-5).

### Ulster County

Ulster County is located in the southeast part of NYS, south of Albany
and immediately west of the Hudson River. Bordered by Greene County to
the north, Delaware County to the northwest, Sullivan County to the
southwest, Orange County to the south, and Dutchess County across the
Hudson River to the east, much of Ulster County can be characterized as
suburban and semi-rural. The county has only one major urban area, the
city of Kingston, located in the eastern central portion of the county,
and encompassing just 7.4 square miles of the county’s total area. The
rest of the county is comprised of 20 towns and three villages. Ulster
County is home to nine school districts and two colleges and
universities within its 1,161-square mile area. See map in [Appendix
G](#section-6).

### Westchester County

Westchester County is located just north of NYC, with an area of about
450 square miles. It is bordered on the west by the Hudson River, on the
north by Putnam County, and on the east by the Long Island Sound and
Connecticut’s Fairfield County. Within its 48 municipalities,
Westchester County can be described as predominately a mix of urban and
suburban communities. Comprised of six cities, 19 towns, and 23
villages, the county is home to 43 public school districts and 24
colleges and universities. See map in [Appendix H](#section-7).
