---
title: "Demographics"
jupyter: python3
execute:
  freeze: auto
---

This chapter summarizes population, age, race/ethnicity, language, income, and other demographic indicators for Orange County and the Mid-Hudson Region.

::: {.panel-tabset}
## Orange County
TODO: Add Orange County demographic highlights and charts.

## Mid-Hudson Region
TODO: Add regional comparisons and key differences across counties.

## New York State
TODO: Add NYS and NYS-excl-NYC benchmarks where available.
:::

## Interactive Table Example
Tables will be manually added by sourcing from the Word document.

## Demographic Summary

#### Population

In 2023, New York State’s (NYS) population was nearly 20 million. When
excluding New York City (NYC), the population was 11,356,117. The
Mid-Hudson Region (M-H Region) made up 12.1% of NYS’ population and
includes the seven counties of Dutchess, Orange, Putnam, Rockland,
Sullivan, Ulster, and Westchester. Westchester County comprised the
largest portion of the M-H Region’s population at 41.6%, while Sullivan
County made up only 3.3% of the M-H Region \[see Table 1\].

The population of the M-H Region grew 4.7% from 2010 to 2020. In those
10 years, growth increased most rapidly in Rockland (7.9%) and Orange
(7.1%). Putnam (-2.1%), and Ulster (-0.4%) had negative growth.

Table 1

| **Population Demographic Characteristics, 2023** |  |  |  |
|----|:--:|:--:|:--:|
| ** ** | **Total Population** | **Percent of Mid-Hudson Region** | **Percent of NYS** |
| **Dutchess** | 297,144 | 12.4 | 1.5 |
| **Orange** | 403,840 | 16.9 | 2.0 |
| **Putnam** | 97,988 | 4.1 | 0.5 |
| **Rockland** | 338,936 | 14.1 | 1.7 |
| **Sullivan** | 79,147 | 3.3 | 0.4 |
| **Ulster** | 182,109 | 7.6 | 0.9 |
| **Westchester** | 996,888 | 41.6 | 5.0 |
| **Mid-Hudson** | 2,396,052 | 100.0 | 12.1 |
| **NYS excl NYC** | 11;356,117 | N/A | 57.1 |
| **NYS** | 19,872,319 | N/A | 100.0 |

Source: US Census Bureau; American Community Survey, 2023 American
Community Survey 5-Year Estimates, Table S0101, April 2025

#### Sex

When stratifying the population by sex in 2023, the M-H Region had a
near-even distribution between males and females \[see Table 2\]. Apart
from Putnam and Sullivan Counties, the M-H Region had a slightly higher
percentage of females than males. The same is true for NYS, as well as
NYS excluding NYC.

Table 2

| **Population by Sex, 2023** |  |  |  |  |
|----|:--:|:--:|:--:|:--:|
| ** ** | **Male** |  | **Female** |  |
| ** ** | **Total Population** | **%** | **Total Population** | **%** |
| **Dutchess** | 147,902 | 49.8 | 149,242 | 50.2 |
| **Orange** | 201,512 | 49.9 | 202,328 | 50.1 |
| **Putnam** | 49,503 | 50.5 | 48,485 | 49.5 |
| **Rockland** | 167,624 | 49.5 | 171,312 | 50.5 |
| **Sullivan** | 40,993 | 51.8 | 38,154 | 48.2 |
| **Ulster** | 90,719 | 49.8 | 91,390 | 50.2 |
| **Westchester** | 485,985 | 48.8 | 510,903 | 51.2 |
| **Mid-Hudson** | 1,184,238 | 49.4 | 1,211,814 | 50.6 |
| **NYS excl NYC** | 5,614,391 | 49.4 | 5,741,726 | 50.6 |
| **NYS** | 9,702,417 | 48.8 | 10,169,902 | 51.2 |

Note: The American Community Survey includes a question that intends to
capture current sex; there are no questions about gender, sexual
orientation, or sex at birth. Respondents should respond either "male"
or "female" based on how they currently identify their sex.

Source: US Census Bureau; American Community Survey, 2023 American
Community Survey 5-Year Estimates, Table S0101, April 2025

https://data.census.gov/table/ACSST5Y2023.S0101?q=s0101&g=050XX00US36105,36027,36071,36119,36087,36079,36111_160XX00US3651000_040XX00US36

#### Age

Throughout the M-H Region, adults aged 50 to 59 years made up the
largest portion of the population (13.8%) \[see Table 3\]. Children aged
less than five years and five to nine years, as well as adults aged 40
to 49 years and 60 to 69 years, were similarly distributed throughout
the M-H Region, with Ulster County having the greatest difference
between adults aged 60 to 69 years and children less than five years old
(14.4% vs 4.4%).

Table 3

| **Population by Age, 2023** |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
|----|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
|   | **\<5 years** |  |  |  | **5-9 years** |  |  |  | **10-19 years** |  |  |  | **20-29 years** |  |  |  |  | **30-39 years** |  |  |  |
| *** *** | **Total Population** |  | **%** |  | **Total Population** |  | **%** |  | **Total Population** |  |  | **%** | **Total Population** |  |  | **%** |  | **Total Population** |  | **%** |  |
| **Dutchess** | 13,613 |  | 4.6 |  | 14,448 |  | 4.9 |  | 37,031 |  |  | 12.5 | 38,178 |  |  | 12.8 |  | 35,520 |  | 12.0 |  |
| **Orange** | 27,143 |  | 6.7 |  | 27,679 |  | 6.9 |  | 61,718 |  |  | 15.3 | 52,658 |  |  | 13.0 |  | 48,459 |  | 12.0 |  |
| **Putnam** | 4,521 |  | 4.6 |  | 4,320 |  | 4.4 |  | 12,426 |  |  | 12.7 | 10,922 |  |  | 11.1 |  | 11,264 |  | 11.5 |  |
| **Rockland** | 28,957 |  | 8.5 |  | 27,051 |  | 8.0 |  | 52,692 |  |  | 15.5 | 41,742 |  |  | 12.3 |  | 38,885 |  | 11.5 |  |
| **Sullivan** | 4,656 |  | 5.9 |  | 4,969 |  | 6.3 |  | 9,343 |  |  | 11.8 | 9,032 |  |  | 11.4 |  | 9,668 |  | 12.2 |  |
| **Ulster** | 7,926 |  | 4.4 |  | 8,802 |  | 4.8 |  | 19,831 |  |  | 10.9 | 22,175 |  |  | 12.2 |  | 23,060 |  | 12.7 |  |
| **Westchester** | 53,282 |  | 5.3 |  | 57,324 |  | 5.8 |  | 129,780 |  |  | 13.0 | 115,269 |  |  | 11.6 |  | 121,312 |  | 12.2 |  |
| **Mid-Hudson** | 140,098 |  | 5.8 |  | 144,593 |  | 6.0 |  | 322,821 |  |  | 13.5 | 289,976 |  |  | 12.1 |  | 288,168 |  | 12.0 |  |
| **NYS excl NYC** | 604,728 |  | 5.3 |  | 640,751 |  | 5.6 |  | 1,454,784 |  |  | 12.8 | 1,442,397 |  |  | 12.7 |  | 1,393,651 |  | 12.3 |  |
| **NYS** | 1,102,961 |  | 5.6 |  | 1,102,946 |  | 5.6 |  | 2,413,200 |  |  | 12.1 | 2,658,703 |  |  | 13.4 |  | 2,751,639 |  | 13.8 |  |
| **Population by Age, 2023 (continued)** |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
|   | **40-49 years** |  |  | **50-59 years** |  |  |  | **60-69 years** |  |  | **70-79 years** |  |  |  | **\>80 years** |  |  |  | **\<18 years** |  |  |
| *** *** | **Total Population** | **%** |  | **Total Population** |  | **%** |  | **Total Population** |  | **%** | **Total Population** |  |  | **%** | **Total Population** |  | **%** |  | **Total Population** |  | **%** |
| **Dutchess** | 36,796 | 12.4 |  | 43,025 |  | 14.5 |  | 41,707 |  | 14.0 | 23,935 |  |  | 8.1 | 12,891 |  | 4.3 |  | 55,342 |  | 18.6 |
| **Orange** | 49,782 | 12.3 |  | 52,995 |  | 13.1 |  | 45,285 |  | 11.2 | 25,081 |  |  | 6.2 | 13,040 |  | 3.2 |  | 103,740 |  | 25.7 |
| **Putnam** | 13,032 | 13.3 |  | 15,538 |  | 15.9 |  | 13,386 |  | 13.7 | 8,739 |  |  | 8.9 | 3,840 |  | 3.9 |  | 19,180 |  | 19.6 |
| **Rockland** | 36,560 | 10.8 |  | 40,115 |  | 11.8 |  | 35,529 |  | 10.5 | 23,713 |  |  | 7.0 | 13,692 |  | 4.0 |  | 99,733 |  | 29.4 |
| **Sullivan** | 9,486 | 12.0 |  | 11,009 |  | 13.9 |  | 10,980 |  | 13.9 | 7,087 |  |  | 9.0 | 2,917 |  | 3.7 |  | 16,947 |  | 21.4 |
| **Ulster** | 22,177 | 12.2 |  | 26,342 |  | 14.5 |  | 26,250 |  | 14.4 | 16,546 |  |  | 9.1 | 9,000 |  | 4.9 |  | 31,636 |  | 17.4 |
| **Westchester** | 133,617 | 13.4 |  | 141,210 |  | 14.2 |  | 121,875 |  | 12.2 | 74,727 |  |  | 7.5 | 48,492 |  | 4.9 |  | 214,739 |  | 21.5 |
| **Mid-Hudson** | 301,450 | 12.6 |  | 330,234 |  | 13.8 |  | 295,012 |  | 12.3 | 179,828 |  |  | 7.5 | 103,872 |  | 4.3 |  | 541,317 |  | 22.6 |
| **NYS excl NYC** | 1,343,897 | 11.8 |  | 1,566,110 |  | 13.8 |  | 1,485,429 |  | 13.1 | 919,800 |  |  | 8.1 | 504,570 |  | 4.4 |  | 2,369,080 |  | 20.9 |
| **NYS** | 2,422,399 | 12.2 |  | 2,638,363 |  | 13.3 |  | 2,425,309 |  | 12.2 | 1,511,287 |  |  | 7.6 | 845,512 |  | 4.3 |  | 4,109,277 |  | 20.7 |

Source: US Census Bureau; American Community Survey, 2023 American
Community Survey 5-Year Estimates, Table S0101, April 2025

<https://data.census.gov/table/ACSST5Y2023.S0101?q=s0101&g=050XX00US36105,36027,36071,36119,36087,36079,36111_160XX00US3651000_040XX00US36>

#### Ethnicity and Race

In 2023, the majority of the population in the M-H Region and NYS were
non-Hispanic White (58.5% and 53.4%, respectively). The Hispanic
population was the second most predominant racial/ethnic group, followed
by the non-Hispanic Black population. Within the M-H Region, Westchester
County had the highest Hispanic population (27.0%), the highest
non-Hispanic Black population (12.9%), and the highest non-Hispanic
Asian population (6.0%). Westchester County’s racial/ethnic profile is
most like that of NYS’; however, the percentage of non-Hispanic Whites
significantly increases when looking at NYS excluding NYC \[see Tables 4
and 5<u>\]</u>.

Table 4

| **Population by Ethnicity, 2023** |  |  |  |  |
|:--:|:--:|:--:|:--:|:--:|
|   | **Hispanic** |  | **Non-Hispanic** |  |
|   | **Total Population** | **%** | **Total Population** | **%** |
| **Dutchess** | 44,153 | 14.9 | 252,991 | 85.1 |
| **Orange** | 93608 | 23.2 | 310,232 | 76.8 |
| **Putnam** | 18,676 | 19.1 | 79,312 | 80.9 |
| **Rockland** | 67,951 | 20.0 | 270,985 | 80.0 |
| **Sullivan** | 14,544 | 18.4 | 64,603 | 81.6 |
| **Ulster** | 21,562 | 11.8 | 160,547 | 88.2 |
| **Westchester** | 269,085 | 27.0 | 727,803 | 73.0 |
| **Mid-Hudson** | 529,579 | 22.1 | 1,866,473 | 77.9 |
| **NYS excl NYC** | 1478113.0 | 13.0 | 9878004.0 | 87.0 |
| **NYS** | 3,898,652 | 19.6 | 15,973,667 | 80.4 |

Note: The Census Bureau collects ethnic data in accordance with
guidelines provided by the US Office of Management and Budget (OMB) and
these data are based on self-identification. For ethnicity, the OMB
standards classify individuals in one of two categories: “Hispanic or
Latino” or “Not Hispanic or Latino.” The Census Bureau uses the term
“Hispanic or Latino” interchangeably with the term “Hispanic,” and also
refer to this concept as “ethnicity.

Source: US Census Bureau; American Community Survey, 2023 American
Community Survey 5-Year Estimates, Table B03002, April 2025

<https://data.census.gov/table/ACSDT5Y2023.B03002?q=b03002&g=050XX00US36105,36027,36071,36119,36087,36079,36111_160XX00US3651000_040XX00US36>

Table 5

| **Population by Race, 2023** |  |  |  |  |  |  |  |  |  |  |
|----|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
|   | **Non-Hispanic White** |  |  | **Non-Hispanic Black or African American** |  | **Non-Hispanic American Indian and Alaskan Native** |  | **Non-Hispanic Asian** |  |  |
| ** ** | Total Population |  | % | Total Population | % | Total Population | % | Total Population |  | % |
| **Dutchess** | 199,670 |  | 67.2 | 28,024 | 9.4 | 222 | 0.07 | 10,044 |  | 3.4 |
| **Orange** | 239,186 |  | 59.2 | 42,478 | 10.5 | 438 | 0.11 | 11,223 |  | 2.8 |
| **Putnam** | 70,948 |  | 72.4 | 2,894 | 3.0 | 81 | 0.08 | 2255 |  | 2.3 |
| **Rockland** | 205,539 |  | 60.6 | 35,626 | 10.5 | 181 | 0.05 | 19,772 |  | 5.8 |
| **Sullivan** | 53,145 |  | 67.1 | 6,263 | 7.9 | 120 | 0.15 | 1584 |  | 2.0 |
| **Ulster** | 133,874 |  | 73.5 | 10,347 | 5.7 | 66 | 0.04 | 3,675 |  | 2.0 |
| **Westchester** | 498,855 |  | 50.0 | 128,199 | 12.9 | 1,197 | 0.12 | 59,912 |  | 6.0 |
| **Mid-Hudson** | 1,401,217 |  | 58.5 | 253,831 | 10.6 | 2,305 | 0.10 | 108,465 |  | 4.5 |
| **NYS excl NYC** | 7,942,876 |  | 69.9 | 934,322 | 8.2 | 21,069 | 0.19 | 518,716 |  | 4.6 |
| **NYS** | 10,608,842 |  | 53.4 | 2,708,094 | 13.6 | 37,212 | 0.19 | 1,754,957 |  | 8.8 |
| **Population by Race, 2023 (continued)** |  |  |  |  |  |  |  |  |  |  |
|   | **Non-Hispanic Native Hawaiian and Other Pacific Islander** |  |  | **Non-Hispanic Other** |  | **Non-Hispanic Two or More Races** |  |  |  |  |
| ** ** | Total Population |  | % | Total Population | % | Total Population |  | % |  |  |
| **Dutchess** | 117 |  | 0.04 | 2,206 | 0.7 | 12,708 |  | 4.3 |  |  |
| **Orange** | 26 |  | 0.01 | 2,563 | 0.6 | 14,318 |  | 3.5 |  |  |
| **Putnam** | 24 |  | 0.02 | 788 | 0.8 | 2322 |  | 2.4 |  |  |
| **Rockland** | 38 |  | 0.01 | 1,921 | 0.6 | 7,908 |  | 2.3 |  |  |
| **Sullivan** | 11 |  | 0.01 | 533 | 0.7 | 2947 |  | 3.7 |  |  |
| **Ulster** | 40 |  | 0.02 | 2,242 | 1.2 | 10,303 |  | 5.7 |  |  |
| **Westchester** | 96 |  | 0.01 | 10,638 | 1.1 | 28,906 |  | 2.9 |  |  |
| **Mid-Hudson** | 352 |  | 0.01 | 20,891 | 0.9 | 79,412 |  | 3.3 |  |  |
| **NYS excl NYC** | 2,610 |  | 0.02 | 70,553 | 0.6 | 387,858 |  | 3.4 |  |  |
| **NYS** | 6,220 |  | 0.03 | 178,956 | 0.9 | 679,386 |  | 3.4 |  |  |

Note: The Census Bureau collects racial data in accordance with
guidelines provided by the US Office of Management and Budget, and these
data are based on self-identification. People who identify with more
than one race may choose to provide multiple races in response to the
race question.

Source: US Census Bureau; American Community Survey, 2023 American
Community Survey 5-Year Estimates, Table B03002, April 2025

<https://data.census.gov/table/ACSDT5Y2023.B03002?q=b03002&g=050XX00US36105,36027,36071,36119,36087,36079,36111_160XX00US3651000_040XX00US36>

#### Spoken Language

According to the *American Community Survey*, the base population for
the spoken language demographic category was people aged five years and
older. Of this population, English was the most common spoken language
in the M-H Region and NYS. A significant portion of the population spoke
a language other than English at home, specifically in Rockland and
Westchester Counties (43.6% and 34.3%, respectively). The Spanish
speaking population was highest in Westchester County (21.0%) compared
to the other counties in the M-H Region \[see Table 6\].

Table 6

| **Population by Spoken Language, 2023** |  |  |  |  |  |  |
|----|:--:|:--:|:--:|:--:|:--:|:--:|
| ** ** | **Only English** |  | **Language other than English** |  | **Spanish** |  |
| ** ** | Total Population | % | Total Population | % | Total Population | % |
| **Dutchess** | 238,585 | 84.1 | 44,946 | 15.9 | 26,003 | 9.2 |
| **Orange** | 266,545 | 70.8 | 110,152 | 29.2 | 55,418 | 15 |
| **Putnam** | 73,860 | 79.0 | 19,607 | 21.0 | 11,733 | 13 |
| **Rockland** | 174,907 | 56.4 | 135,072 | 43.6 | 46,360 | 15.0 |
| **Sullivan** | 59,484 | 79.9 | 15,007 | 20.1 | 8,639 | 12 |
| **Ulster** | 152,966 | 87.8 | 21,217 | 12.2 | 11,924 | 6.8 |
| **Westchester** | 619,503 | 65.7 | 324,103 | 34.3 | 196,271 | 21 |
| **Mid-Hudson** | 1,585,850 | 54.2 | 670,104 | 22.9 | 356,348 | 12.2 |
| **NYS excl NYC** | 8,808,643 | 69.4 | 1,942,746 | 15.3 | 940,527 | 12.2 |
| **NYS** | 13,017,480 | 69.4 | 5,751,878 | 30.6 | 2,762,664 | 15 |

| **Population by Spoken Language, 2023 (continued)** |  |  |  |  |  |  |
|----|:--:|:--:|:--:|:--:|:--:|:--:|
| ** ** | **Other Indo-European languages** |  | **Asian and Pacific Islander languages** |  | **Other languages** |  |
| ** ** | Total Population | % | Total Population | % | Total Population | % |
| **Dutchess** | 10,769 | 3.8 | 5,267 | 1.9 | 2,907 | 1.0 |
| **Orange** | 45,346 | 12 | 6,298 | 1.7 | 3,090 | 0.8 |
| **Putnam** | 5,687 | 6.1 | 1,504 | 1.6 | 683 | 0.7 |
| **Rockland** | 69,600 | 22.5 | 12,024 | 3.9 | 7,088 | 2.3 |
| **Sullivan** | 4,877 | 6.5 | 819 | 1.1 | 672 | 0.9 |
| **Ulster** | 5,602 | 3.2 | 2,679 | 1.5 | 1012 | 0.6 |
| **Westchester** | 78,915 | 8.4 | 32,889 | 3.5 | 16,028 | 1.7 |
| **Mid-Hudson** | 220,796 | 7.5 | 61,480 | 2.1 | 31,480 | 1.1 |
| **NYS excl NYC** | 632,717 | 5.0 | 258,104 | 2.0 | 111,398 | 0.9 |
| **NYS** | 1,679,571 | 8.9 | 958,133 | 5.1 | 351,510 | 1.9 |

Note: The American Community Survey asks respondents to report whether
they sometimes or always spoke a language other than English at home.
People who spoke languages other than English but did not use them at
home, who only used them elsewhere, or whose usage was limited to a few
expressions or slang were excluded.  
Source: US Census Bureau; American Community Survey, 2023 American
Community Survey 5-year estimates, Table S1601, April 2025  
https://data.census.gov/table/ACSST5Y2023.S1601?q=s1601&g=050XX00US36105,36027,36071,36119,36087,36079,36111_160XX00US3651000_040XX00US36

#### Educational Attainment

According to the *American Community Survey*, the base population for
the educational attainment demographic category were people aged 25
years and older \[see Table 7\]. Of this population, when looking at the
M-H Region, NYS, and NYS excluding NYC, the largest portion of residents
had a high school degree (22.4%, 24.6%, and 25.8%, respectively) \[see
Table 7\].

Table 7

| **Population 25 Years and Older, 2023** |                      |
|-----------------------------------------|:--------------------:|
| ** **                                   | **Total Population** |
| **Dutchess**                            |       211,380        |
| **Orange**                              |       258,632        |
| **Putnam**                              |        71,149        |
| **Rockland**                            |       208,594        |
| **Sullivan**                            |        55,761        |
| **Ulster**                              |       134,325        |
| **Westchester**                         |       697,202        |
| **Mid-Hudson**                          |      1,637,043       |
| **NYS excl NYC**                        |      7,905,485       |
| **NYS**                                 |      13,996,138      |

Note: The Census Bureau defines educational attainment as the highest
level of education that an individual has completed. This is distinct
from the level of schooling that an individual is attending.

Source: US Census Bureau; American Community Survey, 2023 American
Community Survey 5-year estimates, Table S1501, April 2025

https://data.census.gov/table/ACSST5Y2020.S1501?q=s1501&g=050XX00US36105,36027,36071,36119,36087,36079,36111_160XX00US3651000_040XX00US36&tid=ACSST5Y2020.S1501

Within the seven counties of the M-H Region, Westchester, Putnam, and
Rockland Counties had the highest percentage of people with bachelor’s
degrees (26.0%, 24.2%, and 23.2%, respectively), while Sullivan had the
lowest percentage (17.0 %). Sullivan, Orange, and Dutchess Counties had
the highest percentage of people with associate degrees (10.3%, 10.3%,
and 10.1%, respectively). A significant portion of the population in the
M-H Region were high school graduates or held a bachelor’s degree \[see
Table 8\].

Table 8

| **Population by Educational Attainment, 2023** |  |  |  |  |  |  |  |  |  |  |  |  |
|----|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
| ** ** | **Less than 9th grade** |  | **9th to 12th grade, no diploma** |  |  |  | **High school graduate or equivalent** |  |  | **Some college, no degree** |  |  |
| *** *** | N | % | N |  | % |  | N |  | % | N |  | % |
| **Dutchess** | 6,262 | 3.0 | 11,055 |  | 5.2 |  | 52,992 |  | 25.1 | 35,689 |  | 16.9 |
| **Orange** | 10,091 | 3.9 | 16,609 |  | 6.4 |  | 72,466 |  | 28.0 | 49,355 |  | 19.1 |
| **Putnam** | 2,255 | 3.2 | 2,536 |  | 3.6 |  | 17,647 |  | 24.8 | 11,728 |  | 16.5 |
| **Rockland** | 11,800 | 5.7 | 13,858 |  | 6.6 |  | 45,118 |  | 21.6 | 33,790 |  | 16.2 |
| **Sullivan** | 2,755 | 4.9 | 4,129 |  | 7.4 |  | 16,623 |  | 29.8 | 9,973 |  | 17.9 |
| **Ulster** | 3,463 | 2.6 | 7,622 |  | 5.7 |  | 37,570 |  | 28.0 | 22,968 |  | 17.1 |
| **Westchester** | 37,761 | 5.4 | 36,459 |  | 5.2 |  | 124,954 |  | 17.9 | 87,534 |  | 12.6 |
| **Mid-Hudson** | 74,387 | 4.5 | 92,268 |  | 5.6 |  | 367,370 |  | 22.4 | 251,037 |  | 15.3 |
| **NYS excl NYC** | 300,738 | 3.8 | 403,754 |  | 5.1 |  | 2,039,454 |  | 25.8 | 1,277,348 |  | 16.2 |
| **NYS** | 836,124 | 6.0 | 862,413 |  | 6.2 |  | 3,437,438 |  | 24.6 | 2,081,783 |  | 14.9 |
| **Population by Educational Attainment, 2023 (continued)** |  |  |  |  |  |  |  |  |  |  |  |  |
| ** ** | **Associate degree** |  |  | **Bachelor’s degree** |  |  |  | **Graduate or professional degree** |  |  |  |  |
| *** *** | N | % |  | N |  | % |  | N |  |  | % |  |
| **Dutchess** | 21,410 | 10.1 |  | 44,414 |  | 21.0 |  | 39,558 |  |  | 18.7 |  |
| **Orange** | 26,722 | 10.3 |  | 46,977 |  | 18.2 |  | 36,412 |  |  | 14.1 |  |
| **Putnam** | 6,002 | 8.4 |  | 17,222 |  | 24.2 |  | 13,759 |  |  | 19.3 |  |
| **Rockland** | 16,169 | 7.8 |  | 48,405 |  | 23.2 |  | 39,454 |  |  | 18.9 |  |
| **Sullivan** | 5,728 | 10.3 |  | 9,476 |  | 17.0 |  | 7,077 |  |  | 12.7 |  |
| **Ulster** | 12,934 | 9.6 |  | 27,094 |  | 20.2 |  | 22,674 |  |  | 16.9 |  |
| **Westchester** | 44,393 | 6.4 |  | 181,482 |  | 26.0 |  | 184,619 |  |  | 26.5 |  |
| **Mid-Hudson** | 133,358 | 8.1 |  | 375,070 |  | 22.9 |  | 343,553 |  |  | 21.0 |  |
| **NYS excl NYC** | 847,708 | 10.7 |  | 1,643,943 |  | 20.8 |  | 1,392,540 |  |  | 17.6 |  |
| **NYS** | 1,242,877 | 8.9 |  | 3,083,769 |  | 22.0 |  | 2,451,734 |  |  | 17.5 |  |

Note: The Census Bureau defines educational attainment as the highest
level of education that an individual has completed. This is distinct
from the level of schooling that an individual is attending.  
Source: US Census Bureau; American Community Survey, 2023 American
Community Survey 5-year estimates, Table S1501, April 2025  
https://data.census.gov/table/ACSST5Y2020.S1501?q=s1501&g=050XX00US36105,36027,36071,36119,36087,36079,36111_160XX00US3651000_040XX00US36&tid=ACSST5Y2020.S1501

#### Income

Income can affect many aspects of life. This includes where people are
able to live, the food and health care coverage available, and almost
every other social determinant of health.

According to the *American Community Survey*, the base population for
the income demographic category were households (all the persons who
occupy a housing unit as their usual place of residence) \[see Table
9\].

Table 9

| **Total Households, 2023** |                |
|----------------------------|:--------------:|
| ** **                      | **Households** |
| **Dutchess**               |    115,184     |
| **Orange**                 |    137,311     |
| **Putnam**                 |     35,054     |
| **Rockland**               |    103,284     |
| **Sullivan**               |     30,215     |
| **Ulster**                 |     73,105     |
| **Westchester**            |    370,256     |
| **Mid-Hudson**             |    864,409     |
| **NYS excl NYC**           |   4,355,640    |
| **NYS**                    |   7,668,956    |

Note: The American Community Survey defines a household as all the
people who occupy a housing unit, such as a house or apartment, as their
usual place of residence (the place where they live most of the time).
This includes both related family members and any unrelated people
living in the same unit.  
Source: US Census Bureau; American Community Survey, 2023 American
Community Survey 5-year estimates, Table S1901, April 2025  
https://data.census.gov/table/ACSST5Y2023.S1901?q=s1901&g=050XX00US36105,36027,36071,36119,36087,36079,36111_160XX00US3651000_040XX00US36

Of this population, the largest portion of households in the M-H Region
had an income greater than \$100,000 in 2023. More than one fifth of the
households in Putnam County were making between \$100,000 and \$149,999
in 2023 (20.9%). There were many households with an income between
\$50,000 and \$74,999 in the M-H Region and NYS; 17.0% of households in
Sullivan County had an income within this bracket \[see Table 10\].

Table 10

| **Households by Income, 2023** |  |  |  |  |  |  |  |  |  |  |  |
|----|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
| ** ** | **\<\$10,000** |  | **\$10,000-\$14,999** |  | **\$15,000-\$24,999** |  | **\$25,000-\$34,999** |  |  | **\$35,000-\$49,999** |  |
|  |  |  |  |  |  |  |  |  |  |  |  |
| ** ** | Total Population | % | Total Population | % | Total Population | % | Total Population | % | Total Population |  | % |
| **Dutchess** | 4,723 | 4.1 | 2,649 | 2.3 | 5,298 | 4.6 | 6,105 | 5.3 | 9,906 |  | 8.6 |
| **Orange** | 5,492 | 4.0 | 4,119 | 3.0 | 8,651 | 6.3 | 7,003 | 5.1 | 10,985 |  | 8.0 |
| **Putnam** | 841.296 | 2.4 | 630.972 | 1.8 | 1,472 | 4.2 | 1,402 | 4.0 | 2,033 |  | 5.8 |
| **Rockland** | 3,822 | 3.7 | 2,169 | 2.1 | 5,784 | 5.6 | 5,474 | 5.3 | 7,746 |  | 7.5 |
| **Sullivan** | 1,420 | 4.7 | 1,481 | 4.9 | 2,327 | 7.7 | 2,447 | 8.1 | 3,384 |  | 11.2 |
| **Ulster** | 4,021 | 5.5 | 2,778 | 3.8 | 4,606 | 6.3 | 4,752 | 6.5 | 7,384 |  | 10.1 |
| **Westchester** | 17,402 | 4.7 | 9,997 | 2.7 | 17,032 | 4.6 | 15,180 | 4.1 | 27,029 |  | 7.3 |
| **Mid-Hudson** | 37,721 | 4.4 | 23,824 | 2.8 | 45,169 | 5.2 | 42,364 | 4.9 | 68,467 |  | 7.9 |
| **NYS excl NYC** | 201,885 | 4.6 | 142,135 | 3.3 | 266,550 | 6.1 | 266,736 | 6.1 | 402,990 |  | 9.3 |
| **NYS** | 437,130 | 5.7 | 314,427 | 4.1 | 498,482 | 6.5 | 475,475 | 6.2 | 697,875 |  | 9.1 |
| **Households by Income, 2023 (continued)** |  |  |  |  |  |  |  |  |  |  |  |
| ** ** | **\$50,000-\$74,999** |  | **\$75,000-\$99,999** |  | **\$100,000-\$149,999** |  | **\$150,000-\$199,999** |  |  | **\>\$200,000** |  |
|  |  |  |  |  |  |  |  |  |  |  |  |
| ** ** | Total Population | % | Total Population | % | Total Population | % | Total Population | % | Total Population |  | % |
| **Dutchess** | 15,780 | 13.7 | 14,513 | 12.6 | 22,346 | 19.4 | 13,822 | 12.0 | 20,042 |  | 17.4 |
| **Orange** | 18,125 | 13.2 | 16,340 | 11.9 | 27,188 | 19.8 | 18,125 | 13.2 | 21,421 |  | 15.6 |
| **Putnam** | 3,926 | 11.2 | 3,365 | 9.6 | 7,326 | 20.9 | 5,503 | 15.7 | 8,553 |  | 24.4 |
| **Rockland** | 11,878 | 11.5 | 10,328 | 10.0 | 18,281 | 17.7 | 12,394 | 12.0 | 25,408 |  | 24.6 |
| **Sullivan** | 5,137 | 17.0 | 3,807 | 12.6 | 4,442 | 14.7 | 2,478 | 8.2 | 3,293 |  | 10.9 |
| **Ulster** | 10,527 | 14.4 | 8,334 | 11.4 | 13,378 | 18.3 | 7,384 | 10.1 | 9,942 |  | 13.6 |
| **Westchester** | 37,766 | 10.2 | 36,285 | 9.8 | 59,241 | 16.0 | 39,988 | 10.8 | 110,336 |  | 29.8 |
| **Mid-Hudson** | 103,139 | 11.9 | 92,973 | 10.8 | 152,202 | 17.6 | 99,694 | 11.5 | 198,996 |  | 23.0 |
| **NYS excl NYC** | 617,645 | 14.2 | 516,423 | 11.9 | 781,447 | 17.9 | 466,426 | 10.7 | 701,072 |  | 16.1 |
| **NYS** | 1,058,316 | 13.8 | 874,261 | 11.4 | 1,288,385 | 16.8 | 774,565 | 10.1 | 1,257,709 |  | 16.4 |

Note: The American Community Survey asks respondents their income in the
past 12 months. Data are provided as a percentage of total households in
Table S1901. Calculations were made to provide data as a number in Table
9.  
Source: US Census Bureau; American Community Survey, 2023 American
Community Survey 5-year estimates, Table S1901, April 2025  
https://data.census.gov/table/ACSST5Y2023.S1901?q=s1901&g=050XX00US36105,36027,36071,36119,36087,36079,36111_160XX00US3651000_040XX00US36

#### Veteran Status

Veteran status includes men and women who served, but are not currently
serving, on active duty in the United States (US) Army, Navy, Air Force,
Marine Corps, or the Coast Guard, or who served in the US Merchant
Marines during World War II. Some issues that veterans experience
following their service include finding a new career path,
reestablishing themselves in society and families, and seeking treatment
for mental health issues. In the M-H Region, Sullivan County had the
highest percentage of civilian veterans (6.0%), double the percentage of
civilian veterans in Rockland and Westchester Counties (3.0% in each)
\[see Table 11\]. Overall, there is a smaller percentage of civilian
veterans in the M-H Region compared to NYS excluding NYC (3.9% vs 5.3%,
respectively).

Table 11

| **Population by Veteran Status, 2023** |  |  |  |
|----|:--:|:--:|:--:|
| ** ** | **Civilian Population 18 Years and Older** | **Civilian Veterans** |  |
| *** *** | Total Population | Total Population | % |
| **Dutchess** | 241,517 | 11,694 | 4.8 |
| **Orange** | 296,319 | 16,695 | 5.6 |
| **Putnam** | 78,712 | 3,320 | 4.2 |
| **Rockland** | 239,088 | 7,130 | 3.0 |
| **Sullivan** | 62,181 | 3,713 | 6.0 |
| **Ulster** | 150,409 | 6,711 | 4.5 |
| **Westchester** | 781,837 | 23,744 | 3.0 |
| **Mid-Hudson** | 1,850,063 | 73,007 | 3.9 |
| **NYS excl NYC** | 8,964,773 | 478,417 | 5.3 |
| **NYS** | 15,737,168 | 607,728 | 3.9 |

Note: The American Community Survey asks respondents if they have ever
served on active duty in the US Armed Forces.  
Source: US Census Bureau; American Community Survey, 2023 American
Community Survey 5-year estimates, Table S2101, April 2025  
https://data.census.gov/table/ACSST5Y2023.S2101?q=s2101+&g=050XX00US36105,36027,36071,36119,36087,36079,36111_160XX00US3651000_040XX00US36

#### Disability

According to the World Health Organization (WHO), disability bears three
dimensions: impairment to body structure or mental function; activity
limitation, such as difficulty hearing, moving, or problem-solving; and
participation restrictions in daily activities, such as working,
engaging in social or recreational activities, or accessing health care
and preventive services. Adults with a disability typically have
higher rates of chronic disease, such as obesity, heart disease, and
diabetes. Structural and societal barriers can limit the ability to
participate in work, recreation, and programs aimed at promoting healthy
living for those living with a disability.

Various types of disabilities can affect an individual’s quality of
life. Types of disability include:

- Independent living disability – difficulty performing tasks or errands
  alone, such as visiting a doctor’s office or shopping due to a
  physical, mental, or emotional condition

- Cognitive disability – serious difficulty concentrating, remembering,
  or making decisions due to a physical, mental, or emotional condition

- Self-care disability – difficulty handling tasks, such as dressing or
  bathing on one’s own

- Ambulatory disability – difficulty moving around physically, such as
  walking or climbing stairs

- Hearing disability – deafness or serious difficulty hearing

- Vision disability – blindness or serious difficulty seeing, even when
  wearing glasses

In the M-H Region, Sullivan County had the highest percentage of adults
living with a disability (15.9%), as well as the highest percentage of
adults living with each of the six types of disabilities; Rockland
County had the lowest percentage of adults living with a disability
(8.7%) \[see Table 12\].

Table 12

| **Percentage of Population by Type of Disability, 2023** |  |  |  |  |  |  |  |
|----|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
|   | **Total with Any Disability** | **Hearing Difficulty** | **Vision Difficulty** | **Cognitive Difficulty** | **Ambulatory Difficulty** | **Self-care Difficulty** | **Independent Living Difficulty** |
| **Dutchess** | 12.2 | 3.5 | 2.0 | 4.7 | 6.3 | 2.6 | 5.9 |
| **Orange** | 11.7 | 3.2 | 2.1 | 5.4 | 6.3 | 2.9 | 6.2 |
| **Putnam** | 9.6 | 2.8 | 1.4 | 3.5 | 5.4 | 2.4 | 4.6 |
| **Rockland** | 8.7 | 2.7 | 1.4 | 3.4 | 4.4 | 2.2 | 4.5 |
| **Sullivan** | 15.9 | 4.4 | 3.0 | 6.4 | 9.1 | 3.7 | 7.2 |
| **Ulster** | 14.4 | 4.2 | 2.3 | 5.1 | 7.4 | 3.0 | 6.0 |
| **Westchester** | 9.5 | 2.5 | 1.6 | 3.7 | 5.3 | 2.3 | 4.8 |
| **Mid-Hudson** | 10.2 | 2.8 | 1.7 | 3.8 | 5.2 | 2.3 | 3.9 |
| **NYS** | 11.6 | 2.8 | 2.1 | 4.5 | 6.6 | 2.7 | 5.7 |

Note: Respondents who report any one of the six disability types are
considered to have a disability in the American Community Survey.  
Source: US Census Bureau; American Community Survey, 2020 American
Community Survey 5-year estimates, Table S1810, April 2025  
https://data.census.gov/table?q=s1810&g=050XX00US36105,36027,36071,36119,36087,36079,36111_160XX00US3651000_040XX00US36
