---
title: "Mid-Hudson Regional Community Health Assessment 2025"
jupyter: python3
execute:
  freeze: false
page-layout: full
---

::: {.hero}
A living, data-driven assessment of the Mid-Hudson Region's health status, priorities, and community conditions.
:::

## Population Focus for The Mid-Hudson Region Community Health Assessment

-   Dutchess County
-   Orange County
-   Putnam County
-   Rockland County
-   Sullivan County
-   Ulster County
-   Westchester County

## Questions or Comments regarding the assessment

For questions pertaining to Dutchess County, please contact:

**Jennifer Conflitti, MPH**

> Epidemiologist
> jconflitti@dutchessny.gov

For questions pertaining to Orange County, please contact:

**Jackie Lawler, MPH, CPH**

> Director of Epidemiology and Public Health Planning\
> JLawler\@orangecountygov.com\

For questions pertaining to Putnam County, please contact:

**Alison Kaufman, DVM, MPH**

> Senior Epidemiologist
> Alison.kaufman@putnamcountyny.gov

For questions pertaining to Rockland County, please contact:
**Peter Hornberger, MPH**

> Director of Epidemiology and Public Health Planning
> Hornberp@co.rockland.ny.us

For questions pertaining to Sullivan County, please contact:
**Jessie Moore, DrPH, MPH, CHES**

> Public Health Director
> Jessie.Moore@sullivanny.gov

For questions pertaining to Westchester County, please contact: 
**Jiali Li, Ph.D., M.A.**

> Director of Research and Evaluation
> JAL6@westchestercountyny.gov